### ISSUE TITLE
String-Map issue

### ISSUE THREAD

**Issue by muthiahm227** [corunet/kloadgen#15]
In the Avro Field and Expression Mappings - Kafka Load Generator Config, for the String-Map field whatever value that we give it gets duplicated or split and sent. We are not able to send the data properly. 
For eg, if we have field name as "ExcelValues" and field type as "string-map" and if we give this in the field value list [{"area":"LASK","area":"JSKL"}] then it goes to kafka as {"area":"LASK"}:{"area":"LASK"} or some times only one key-pair values. 
Is it something that, we are not properly formatting and supplying the values, or is it an issue with string-map format? Please let us know.

**Comment by kszosze** [comment]
Hi Muthiahm,
We will take a look. 
The field Value List is used for our Randon Generator Value as a set of possible values to fill the field. Size of the map can be set in the Size Column, but if you let it at 0 a random size is choose.
Can you please provide us the JMX file you are using or at least a screnshot of the properties table?
Thanks in advance.

**Comment by muthiahm227** [comment]
Hi Kszosze, Thanks for the reply. Due to client restrictions, i cannot post the screenshot or share the JMX. But in properties I havent changed anything apart from the first 3 params (bootstrap,zookeeper and topic)
In the field value list, i wish to give a standard set of values that needs to be pushed to the kafka topic, instead of a random value. I hope it is possible, please clarify. I tried with many possible ways of sending the string map with two key-value pairs but with no success. Following are ways through which i tried,
[{"Key1_MyKey":"Value1_MyValue"},{"Key2_MyKey":"Value2_MyValue"}]
[{"Key1_MyKey"}:{"Value1_MyValue"},{"Key2_MyKey"}:{"Value2_MyValue"}]
["Key1_MyKey":"Value1_MyValue","Key2_MyKey":"Value2_MyValue"]
[Key1_MyKey:Value1_MyValue,Key2_MyKey:Value2_MyValue]
["Key1_MyKey" : "Value1_MyValue", "Key2_MyKey" : "Value2_MyValue"]

**Comment by kszosze** [comment]
Hi Muthiahm,
I just have a proposal in a branch for this issue. Can you please try it?
The behaviour of the plugin, in that branch, requires you include the values as [Key1_MyKey:Value1_MyValue,Key2_MyKey:Value2_MyValue]
so the tool will choose values from that list to fill a map. 
if you define a map of size1, it will choose 1 of those values and insert it. if you define a map of size 3 it will be choosing from the list and create a map of size 3.
That behaviour suits you?

**Comment by muthiahm227** [comment]
Hi Kszosze,

Thanks for looking into this. I took the latest code and built JAR and tried executing the test. I am getting an error that "Error serializing Avro message". Please refer the stack trace below.

```
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.ClassCastException: org.apache.avro.generic.GenericData$EnumSymbol cannot be cast to java.lang.CharSequence
	at org.apache.avro.generic.GenericDatumWriter.writeString(GenericDatumWriter.java:323) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeString(GenericDatumWriter.java:315) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:150) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:144) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:206) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:195) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:130) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:206) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:195) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:130) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82) ~[kloadgen-1.1.0.jar:?]
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:72) ~[kloadgen-1.1.0.jar:?]
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:92) ~[kloadgen-1.1.0.jar:?]
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53) ~[kloadgen-1.1.0.jar:?]
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62) ~[kafka-clients-2.4.1.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:903) ~[kafka-clients-2.4.1.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865) ~[kafka-clients-2.4.1.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752) ~[kafka-clients-2.4.1.jar:?]
	at net.coru.kloadgen.sampler.ConfluentKafkaSampler.runTest(ConfluentKafkaSampler.java:239) [kloadgen-1.1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:199) [ApacheJMeter_java.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-05-05 11:01:38,396 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group-New 1-1
2020-05-05 11:01:38,396 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group-New 1-1
2020-05-05 11:01:38,396 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-05-05 11:01:38,397 INFO o.a.k.c.p.KafkaProducer: [Producer clientId=producer-6] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2020-05-05 11:01:38,400 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

```

**Comment by kszosze** [comment]
Hi Muthiahm,
That looks a different problem than the map one. I'm assuming you got the branch, compile it and run the test. 
What this error means, is you had an Enum type defined in your Schema, but when you are trying to serialize the defined type is a String (or CharSequente) so it is not compatible. Like a ClassCastException.
Now I really need a similar schema with similar properties and a jmx in order to analyze this case. 
We can follow this thread, but if the Map generation works (what I'm asssuming) I'm wondering if we can close this issue and open other one with the data I need.
Regards.

**Comment by muthiahm227** [comment]
Hi Kszosze,
I am not sure whether this is a separate issue or not, because we haven't faced this issue with the previous jar that we used. this issue we are getting only from the current version of code. And there is no change in our schema/code.

**Comment by kszosze** [comment]
Hi Muthiahm,
it's really strange. I need an example of the failing schema. Can you provide it? The stacktrace looks extrange I'm trying to figure out how to replicate. You are using the code from this issue branch, right?
Regards

**Comment by kszosze** [comment]
Hi Muthiahm,
I just do deeper and I found a bug. I'll prepare a fix during the day.
Sorry for the problems. 
I'll keep you posted.
Regards

**Comment by kszosze** [comment]
Hi Muthiahm,
Fix committed. If you don't mind to try it, I guess it will work fine.
I'll be waiting for your feedback.
Regards

**Comment by muthiahm227** [comment]
Hi Kszosze,
Thanks for your time and fixing this. Now, I am able to push messages successfully  :-) and I no longer get TypeCast issue or wrongly formatted message. 
But one small issue that I still see is that, for a specific string-map, i have to send close to 25 key-value pairs and when i try to send that, the tool randomly picks some 4-5 values only and sends it, i tried changing the field length to multiple values like 25, 50 and 700 (the entire content length), but it always picks some random key-value pairs only. Not sure why this behavior is, but if i send 2-3 key value pairs only, then it gets submitted as it is. Can you let me know is it something to do with the "Field Length" values or is it an issue?

**Comment by kszosze** [comment]
Hi Muthiahm,
good to know is working.
About field Length, in case of maps it's a bit controversial.
This property meaning is Length of the generated data, for example in case of String Field means string not bigger than the specified. Same for Integer values or so.
Arrays and Maps are more or less similar, but now we only have length implementation for arrays, you specify a number between the first pair of [] and that will set the array length. 
For maps we didn't face that situation, but we can implement similar feature.
For now Map length is a random number top to 5.
If you need to define a fixed number of elements in the map, I'll ask you to requested in a specific ticket/issue. Just to coordinate the tasks
Regards!

**Comment by muthiahm227** [comment]
Hey, thanks for the help, let me open one more thread to increase the string-map field to the set values, instead of "random number top to 5"

**Comment by muthiahm227** [comment]
Hi Kszosze, Thanks for your helep. Will you be able to look at the other issue as well - "String-Map - Send preset values", which I have explained in this thread also?

**Comment by kszosze** [comment]
Hi Muthiahm,
We are already on it. Just doing the changes. I hope early next week we are gonna have something already.
Regards.

**Comment by muthiahm227** [comment]
Great thanks.
